### ISSUE TITLE
Hot reload not working!

### ISSUE THREAD

**Issue by LinArcX** [torta/flutter-lazy.vim#1]
Hi. i try your plugin but it only format the document when i save it. how use hot reload feature?

**Comment by torta** [comment]
Thanks for your report.
Hot Reload is just sending a SIGUSR1 to flutter_tool process.
Execute the commands when flutter is running may help to find issues.

```
pgrep -f flutter_tool
pgrep -f flutter_tool | xargs kill -s USR1
```

**Comment by LinArcX** [comment]
Every thing is fine(Hot reload working well) when i run those commands in terminal!

**Comment by LinArcX** [comment]
I'v just create this funciton and its work well properly:
```
function! HotReload()
     execute ":silent !pgrep -f flutter_tool | xargs kill -s USR1"
endfunction
nmap <leader>l :call HotReload()<CR
```

**Comment by torta** [comment]
I found the issue when your vim shell=dash or shell=sh and /bin/sh is a symlink to /bin/dash.

The latest version fixed this issue.
thank you.

**Comment by LinArcX** [comment]
Your welcome:) i'm curious how to _hot restart_ the app! do you know about it?

**Comment by torta** [comment]
You can Hot Restart flutter by sending SIGUSR2 to flutter_tool process.

```
pgrep -f flutter_tool | xargs kill -s USR2
```
